<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-O8RAVM4" failures="0" tests="2" name="UI_Test_Class.TC_Linkedin" time="0.056" errors="1" timestamp="2024-11-23T00:05:44 IST" skipped="1">
  <testcase classname="UI_Test_Class.TC_Linkedin" name="testSetUp" time="0.056">
    <error message="Error reading YAML file: Resources/Variable.yaml" type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException: Error reading YAML file: Resources/Variable.yaml
at Common_Utilities.Utility_Methods.readYamlFile(Utility_Methods.java:150)
at UI_Test_Class.TC_Linkedin.testSetUp(TC_Linkedin.java:36)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:644)
at org.testng.TestRunner.beforeRun(TestRunner.java:633)
at org.testng.TestRunner.run(TestRunner.java:595)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.io.FileNotFoundException: Resources\Variable.yaml (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
at Common_Utilities.Utility_Methods.readYamlFile(Utility_Methods.java:147)
... 23 more
]]>
    </error>
  </testcase> <!-- testSetUp -->
  <system-out/>
  <testcase classname="UI_Test_Class.TC_Linkedin" name="launchLinkedIN" time="0.000">
    <skipped/>
  </testcase> <!-- launchLinkedIN -->
  <system-out/>
</testsuite> <!-- UI_Test_Class.TC_Linkedin -->
